id: I48C9A454
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:05:32.627580'
last_modified: '2022-06-18T20:05:32.627593'
parser: null
source_metadata:
  title: Commentary of the Essential Meaning of the Kālacakratantra (Old rGyal bzang
    smon mkhar block print), colophon excerpt
  author: འགོས་ལོ་ཙཱ་བ་གཞོན་ནུ་དཔལ།
  description: 'Digital version 1.0 {Tibetan}, diplomatic edition of witness A; master
    xml (completed: 2020-07-23); revision in process, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:བློ་བཟང་རྒྱལ་མཚན། (Dharamsala) (lg)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:བློ་བཟང་རྒྱལ་མཚན། (Dharamsala) (lg)
  text_witnesses: https://sakyaresearch.org/sources/4842
  bases:
    dcce:
      title: Commentary of the Essential Meaning of the Kālacakratantra (Old rGyal
        bzang smon mkhar block print), colophon excerpt
      order: 1
      base_file: dcce.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
